image: python:latest


stages:
  - test
  - deploy

py3.4:
  stage: test
  image: python:3.4-stretch
  before_script:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
  script:
  - pipenv run pytest .

py3.5:
  stage: test
  image: python:3.5-stretch
  before_script:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
  script:
  - pipenv run pytest .

py3.6:
  stage: test
  image: python:3.6-stretch
  before_script:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
  script:
  - pipenv run pytest .

pypi_deploy:
  stage: deploy
  only:
  - master
  before_script:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
  - rm -rf dist
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers =" >> ~/.pypirc
  - echo "    pypi" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[pypi]" >> ~/.pypirc
  - echo "${PYPI_REPO}" >> ~/.pypirc
  - echo "${PYPI_USER}" >> ~/.pypirc
  - echo "${PYPI_PASSWORD}" >> ~/.pypirc
  script:
  - pipenv run python setup.py sdist bdist_wheel
  - pipenv run twine upload -r pypi dist/*