image: python:3.6-stretch


stages:
  - deploy

pypi_deploy:
  stage: deploy
  only:
  - master
  before_script:
  - pip install pipenv
  - pipenv install
  - pipenv install --skip-lock twine
  - rm -rf dist
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers =" >> ~/.pypirc
  - echo "    pypi" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[pypi]" >> ~/.pypirc
  - echo "repository: ${PYPI_REPO}" >> ~/.pypirc
  - echo "username: ${PYPI_USER}" >> ~/.pypirc
  - echo "password: ${PYPI_PASSWORD}" >> ~/.pypirc
  script:
  - pipenv run python setup.py check sdist bdist  # This will fail if your creds are bad.
  - pipenv run python setup.py sdist bdist_wheel
  - pipenv run twine upload -r pypi dist/*