image: python:3.6-stretch


stages:
  - test
  - deploy

py36:
  stage: test
  before_script:
  - pip install pipenv
  - pipenv install --dev
  script:
  - pipenv run python ./simplex/simplex.py

pypi_deploy:
  stage: deploy
  only:
  - master
  before_script:
  - pip install pipenv
  - pipenv install --dev
  - rm -rf dist
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers =" >> ~/.pypirc
  - echo "    pypi" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[pypi]" >> ~/.pypirc
  - echo "${PYPI_REPO}" >> ~/.pypirc
  - echo "${PYPI_USER}" >> ~/.pypirc
  - echo "${PYPI_PASSWORD}" >> ~/.pypirc
  script:
  - pipenv run python setup.py sdist bdist_wheel
  - pipenv run twine upload -r pypi dist/*